#!/bin/bash
# Copyright 2006 Daniel Benamy <dbenamy1@binghamton.edu>
# License to be determined

# Exit codes:
# 0 Ok
# 3 Invalid name
# 4 Name not unique
# 5 Error allocating id
# 6 Invalid IP address
# 7 IP Address not in allowable range
# 8 Error writing new entry

# TODO figure out directory of this script and work relative to that.
# Current setup won't work if run from the wrong directory.
. conf/contest.conf
#echo $0
#echo `dirname $0`

if [-z "$1"] then
	exit 3
fi
name=${1}

# Make sure user name contains only letters, numbers, or space
echo ${name} | grep [^0-9A-Za-z\ ]
if ["$?" -eq 0] then
	exit 3
fi

# Make sure it's unique
cat ${ROOT}/manager/conf/users.txt | awk -F ':' '{print $2}' | grep ${name}
if ["$?" -eq "0"] then
	exit 4
fi

id=`${ROOT}/manager/genid`
if ["$?" -ne "0"] then
	exit 5
fi

if [-z "${2}"] then
	exit 6
fi
ip=${2}

# TODO Make sure ip address is valid
# Reg exp from http://www.regular-expressions.info/examples.html
echo "${ip} | grep \b\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}\b
echo $?

# Make sure it's in allowable range if one is given
if [-n "$ALLOWABLE_IPS"] then
	echo $ip | grep ${ALLOWABLE_IPS}
	if [$? -ne 0] then
		exit 7
	fi
fi

echo "${id}:${1}" >> ${ROOT}/manager/conf/users.txt
if [$? -ne 0] then
	exit 8
fi

exit 0
