#!/usr/bin/env bash
if [ $# == 0 ]; then
	exit	
fi
FILE=$1
PROB=`dirname $1`
BASE=`basename ${FILE}`
JAVA=`basename ${BASE} .java`
MAKE=${BASE}.make
while read LINE
do
	ID=`echo ${LINE} | awk -F ':' '{print $1}'`
	NAME=`echo ${LINE} | awk -F ':' '{print $2}'`
	echo "s/${ID}/${NAME}/g"
done < handles > user_translation.tmp
ID=`echo ${BASE} | awk -F '-' '{print $1}'`
NAME=`echo ${BASE} | awk -F '-' '{print $1}' | sed -f user_translation.tmp`
rm user_translation.tmp -f
TIME=`echo ${BASE} | awk -F '-' '{print $2}'`
TIME=`basename ${TIME} .c`
TIME=`basename ${TIME} .cpp`
TIME=`basename ${TIME} .java`
VERIFY="../mydiff"

TIMEOUT=30
OUTFILE=output.txt

LOG="../logs/compiles/${BASE}.log"

rm testing -rf
mkdir testing
cp ${FILE}* testing/
cp ${PROB}/*output testing/
cp ${PROB}/*input testing/
cd testing/

if [ ${JAVA} != ${BASE} ]; then
	mv ${BASE} ${PROB}.java
	EXEC="../executor ./${PROB}.class"
else
	EXEC="../executor ./a.out"
fi

while read line; do
        ${line} &> ../${LOG}
done < ${MAKE}

if [ $? != 0 ]; then
	echo "${TIME},${ID},${NAME},${PROB},1,${LOG},Error Compiling"
	exit 1	
fi

STATUS=0
MESSAGE=Success
for INPUT in *.input; do
	OUTPUT=`basename ${INPUT} .input`.output
	${EXEC} ${INPUT} ${OUTFILE} ${TIMEOUT} > /dev/null
	if [ $? == 1 ]; then
		STATUS=4
		MESSAGE="${INPUT}-Program crashed"
		break
		#echo "${TIME},${NAME},${PROB},4,${INPUT},Program crashed"
		#exit 1
	fi
	if [ $? == 2 ]; then
		STATUS=3
		MESSAGE="${INPUT}-Program timed out"
		break
		#echo "$TIME, ${NAME}, ${PROB},3,${INPUT},Program timed out"
		#exit 1
	fi 
	if [ $? != 0 ]; then
		STATUS=15
		MESSAGE="${INPUT}-Unknown Error"
		break
	fi
	${VERIFY} ${OUTFILE} ${OUTPUT} > /dev/null
	if [ $? != 0 ]; then
		STATUS=2
		MESSAGE="${INPUT}-Output is not as expected"
		break
		#echo "${TIME},${NAME},${PROB},2,${INPUT},Output is not as expected." 
		#exit 1
	fi
done
echo "${TIME},${ID},${NAME},${PROB},${STATUS},${MESSAGE}"

