#!/usr/bin/env bash
# Generates a user ID that is Between MOD and LOWER
# The ID must not already be in users.txt.
ID=$RANDOM
ID=0
MOD=10000 # Change to reflect the number of digits you want.
LOWER=1000

while [ true ]; do
    #Generate our ID.
    while [ "$ID" -le $LOWER ]; do
        let "ID=$RANDOM % $MOD"
    done

    #Check if the ID is in use.
    grep $ID users.txt

    if [ $? == 1 ]; then
        echo $ID
        break 
    fi
done
