#!/usr/bin/env bash

# Read the contents of CONF_FILE (which is in the .ini format)
# and retrieve the variables named in VARS[] and places them inside
# the variable with the same name in bash.

# Example:
# Reads ROOT out of contest.ini and then sets $ROOT to be
# what is set in contest.ini

CONF_FILE=conf/contest.ini

# Reads the variable out of CONF_FILE and evaluates it.
read_var() {
  local NAME 
  NAME=$1
  VAR=`echo "$1" | tr [A-Z] [a-z]`
  VAR=`./parse_ini $CONF_FILE s=global k=$VAR`
  eval ${NAME}="$VAR"
}


# Reads all the options available in CONF_FILE's global section
# and then sets us up to use them.
for option in `./parse_ini $CONF_FILE o=global`; do
  OPT="`echo $option | tr [:lower:] [:upper:]`"
  read_var $OPT;
  export "${OPT}"="${VAR}"
done
